#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ROOT_DIR="${RELAX_ROOT_DIR:-$(cd -- "${SCRIPT_DIR}/../../.." &>/dev/null && pwd)}"
BASE_LAUNCHER="${SCRIPT_DIR}/amd_qwen3_0_6b_4gpu_e2e.sh"
RUN_ID="${PROFILE_RUN_ID:-$(date '+%Y%m%d_%H%M%S')}"
PROFILE_NAME="${PROFILE_NAME:-qwen3-0.6b-fully-async-${RUN_ID}}"
PROFILE_ROOT="${PROFILE_ROOT:-${ROOT_DIR}/profiling_results/${PROFILE_NAME}}"
mkdir -p "${PROFILE_ROOT}"
PROFILE_ROOT="$(cd -- "${PROFILE_ROOT}" &>/dev/null && pwd)"
PROFILE_APPEND="${PROFILE_APPEND:-0}"

RUN_LOG="${PROFILE_ROOT}/run.log"
LAUNCH_ENV="${PROFILE_ROOT}/launch.env"
TIMELINE_DIR="${PROFILE_ROOT}/timeline"
SGLANG_TRACE_DIR="${PROFILE_ROOT}/sglang_trace"
TRACE_EXPERIMENT_NAME="${TRACE_EXPERIMENT_NAME:-${PROFILE_NAME}}"
TB_EXPERIMENT_NAME="${RELAX_TB_EXPERIMENT_NAME:-${PROFILE_ROOT}/traces/${TRACE_EXPERIMENT_NAME}}"
RELAX_PROFILE_PASS="${RELAX_PROFILE_PASS:-both}"

mkdir -p "${TIMELINE_DIR}" "${SGLANG_TRACE_DIR}" "${PROFILE_ROOT}/traces"
if [[ "${PROFILE_APPEND}" != "1" || ! -f "${RUN_LOG}" ]]; then
    : > "${RUN_LOG}"
fi

USER_RELAX_TIMELINE_DUMP_DIR="${RELAX_TIMELINE_DUMP_DIR:-}"
USER_RELAX_USE_PYTORCH_PROFILER="${RELAX_USE_PYTORCH_PROFILER:-}"
USER_RELAX_PROFILE_TARGETS="${RELAX_PROFILE_TARGETS:-}"
USER_RELAX_PROFILE_STEP_START="${RELAX_PROFILE_STEP_START:-}"
USER_RELAX_PROFILE_STEP_END="${RELAX_PROFILE_STEP_END:-}"
USER_RELAX_PROFILE_WITH_STACK="${RELAX_PROFILE_WITH_STACK:-}"
USER_RELAX_PROFILE_WITH_MEMORY="${RELAX_PROFILE_WITH_MEMORY:-}"
USER_RELAX_PROFILE_WITH_FLOPS="${RELAX_PROFILE_WITH_FLOPS:-}"
USER_RELAX_SGLANG_PROFILE="${RELAX_SGLANG_PROFILE:-}"
USER_RELAX_SGLANG_PROFILE_STEP_START="${RELAX_SGLANG_PROFILE_STEP_START:-}"
USER_RELAX_SGLANG_PROFILE_STEP_END="${RELAX_SGLANG_PROFILE_STEP_END:-}"
USER_RELAX_SGLANG_PROFILE_STEPS="${RELAX_SGLANG_PROFILE_STEPS:-}"
USER_RELAX_SGLANG_PROFILE_NUM_STEPS="${RELAX_SGLANG_PROFILE_NUM_STEPS:-}"
USER_RELAX_SGLANG_PROFILE_ACTIVITIES="${RELAX_SGLANG_PROFILE_ACTIVITIES:-}"
USER_RELAX_SGLANG_PROFILE_BY_STAGE="${RELAX_SGLANG_PROFILE_BY_STAGE:-}"
USER_RELAX_SGLANG_PROFILE_WITH_STACK="${RELAX_SGLANG_PROFILE_WITH_STACK:-}"
USER_RELAX_SGLANG_PROFILE_RECORD_SHAPES="${RELAX_SGLANG_PROFILE_RECORD_SHAPES:-}"
USER_RELAX_SGLANG_PROFILE_OUTPUT_DIR="${RELAX_SGLANG_PROFILE_OUTPUT_DIR:-}"

export RELAX_ROOT_DIR="${ROOT_DIR}"
export CONDA_ENV_NAME="${CONDA_ENV_NAME:-relaxrl_rocm_after_fix}"
export MODEL_CONFIG_NAME="${MODEL_CONFIG_NAME:-qwen3-0.6B}"
export MODEL_ASSET_NAME="${MODEL_ASSET_NAME:-Qwen3-0.6B}"
export MODEL_LOG_NAME="${MODEL_LOG_NAME:-qwen3-0.6b}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export WANDB_ENTITY="${WANDB_ENTITY:-}"
DEFAULT_RELAX_SGL_KERNEL_BUILD_DIR="/vast/users/qirong.ho/erland/Python_project"
DEFAULT_RELAX_SGL_KERNEL_BUILD_DIR+="/sglang/sgl-kernel/build/lib.linux-x86_64-cpython-312"
export RELAX_SGL_KERNEL_BUILD_DIR="${RELAX_SGL_KERNEL_BUILD_DIR:-${DEFAULT_RELAX_SGL_KERNEL_BUILD_DIR}}"

export RELAX_HIP_VISIBLE_DEVICES_OVERRIDE="${RELAX_HIP_VISIBLE_DEVICES_OVERRIDE:-${HIP_VISIBLE_DEVICES:-0,1,2,3}}"
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-${RELAX_HIP_VISIBLE_DEVICES_OVERRIDE}}"
export RAY_NUM_GPUS="${RAY_NUM_GPUS:-4}"
export NUM_GPUS_PER_NODE="${NUM_GPUS_PER_NODE:-4}"
export ACTOR_RESOURCE_GPUS="${ACTOR_RESOURCE_GPUS:-2}"
export ROLLOUT_RESOURCE_GPUS="${ROLLOUT_RESOURCE_GPUS:-1}"
export ACTOR_FWD_RESOURCE_GPUS="${ACTOR_FWD_RESOURCE_GPUS:-1}"
export RELAX_EXECUTION_MODE="${RELAX_EXECUTION_MODE:-fully_async}"
export MAX_STALENESS="${MAX_STALENESS:-1}"
export NUM_ROLLOUT="${NUM_ROLLOUT:-3}"
export NO_SAVE_RNG="${NO_SAVE_RNG:-1}"

export RUN_LOG
export RUN_LOG_APPEND=1

write_launch_env() {
    {
        echo "PROFILE_ROOT=${PROFILE_ROOT}"
        echo "PROFILE_NAME=${PROFILE_NAME}"
        echo "PROFILE_APPEND=${PROFILE_APPEND}"
        echo "RELAX_PROFILE_PASS=${RELAX_PROFILE_PASS}"
        echo "RUN_LOG=${RUN_LOG}"
        echo "LAUNCH_ENV=${LAUNCH_ENV}"
        echo "CONDA_ENV_NAME=${CONDA_ENV_NAME}"
        echo "WANDB_MODE=${WANDB_MODE}"
        echo "WANDB_ENTITY=${WANDB_ENTITY}"
        echo "RELAX_SGL_KERNEL_BUILD_DIR=${RELAX_SGL_KERNEL_BUILD_DIR}"
        echo "HIP_VISIBLE_DEVICES=${HIP_VISIBLE_DEVICES}"
        echo "RAY_NUM_GPUS=${RAY_NUM_GPUS}"
        echo "NUM_GPUS_PER_NODE=${NUM_GPUS_PER_NODE}"
        echo "ACTOR_RESOURCE_GPUS=${ACTOR_RESOURCE_GPUS}"
        echo "ROLLOUT_RESOURCE_GPUS=${ROLLOUT_RESOURCE_GPUS}"
        echo "ACTOR_FWD_RESOURCE_GPUS=${ACTOR_FWD_RESOURCE_GPUS}"
        echo "RELAX_EXECUTION_MODE=${RELAX_EXECUTION_MODE}"
        echo "MAX_STALENESS=${MAX_STALENESS}"
        echo "NUM_ROLLOUT=${NUM_ROLLOUT}"
        echo "NO_SAVE_RNG=${NO_SAVE_RNG}"
        echo "RELAX_TB_EXPERIMENT_NAME=${TB_EXPERIMENT_NAME}"
        echo "RELAX_TIMELINE_DUMP_DIR=${USER_RELAX_TIMELINE_DUMP_DIR:-${TIMELINE_DIR}}"
        echo "PASS1_RELAX_USE_PYTORCH_PROFILER=${USER_RELAX_USE_PYTORCH_PROFILER:-0}"
        echo "PASS1_RELAX_SGLANG_PROFILE=${USER_RELAX_SGLANG_PROFILE:-0}"
        echo "PASS2_RELAX_USE_PYTORCH_PROFILER=${USER_RELAX_USE_PYTORCH_PROFILER:-1}"
        echo "PASS2_RELAX_PROFILE_TARGETS=${USER_RELAX_PROFILE_TARGETS:-train_overall train_actor train_log_probs}"
        echo "PASS2_RELAX_PROFILE_STEP_START=${USER_RELAX_PROFILE_STEP_START:-1}"
        echo "PASS2_RELAX_PROFILE_STEP_END=${USER_RELAX_PROFILE_STEP_END:-2}"
        echo "PASS2_RELAX_PROFILE_WITH_STACK=${USER_RELAX_PROFILE_WITH_STACK:-0}"
        echo "PASS2_RELAX_PROFILE_WITH_MEMORY=${USER_RELAX_PROFILE_WITH_MEMORY:-0}"
        echo "PASS2_RELAX_PROFILE_WITH_FLOPS=${USER_RELAX_PROFILE_WITH_FLOPS:-0}"
        echo "PASS2_RELAX_SGLANG_PROFILE=${USER_RELAX_SGLANG_PROFILE:-1}"
        echo "PASS2_RELAX_SGLANG_PROFILE_STEP_START=${USER_RELAX_SGLANG_PROFILE_STEP_START:-1}"
        echo "PASS2_RELAX_SGLANG_PROFILE_STEP_END=${USER_RELAX_SGLANG_PROFILE_STEP_END:-2}"
        echo "PASS2_RELAX_SGLANG_PROFILE_STEPS=${USER_RELAX_SGLANG_PROFILE_STEPS:-}"
        echo "PASS2_RELAX_SGLANG_PROFILE_NUM_STEPS=${USER_RELAX_SGLANG_PROFILE_NUM_STEPS:-3}"
        echo "PASS2_RELAX_SGLANG_PROFILE_ACTIVITIES=${USER_RELAX_SGLANG_PROFILE_ACTIVITIES:-CPU GPU}"
        echo "PASS2_RELAX_SGLANG_PROFILE_BY_STAGE=${USER_RELAX_SGLANG_PROFILE_BY_STAGE:-0}"
        echo "PASS2_RELAX_SGLANG_PROFILE_WITH_STACK=${USER_RELAX_SGLANG_PROFILE_WITH_STACK:-0}"
        echo "PASS2_RELAX_SGLANG_PROFILE_RECORD_SHAPES=${USER_RELAX_SGLANG_PROFILE_RECORD_SHAPES:-0}"
        echo "PASS2_RELAX_SGLANG_PROFILE_OUTPUT_DIR=${USER_RELAX_SGLANG_PROFILE_OUTPUT_DIR:-${SGLANG_TRACE_DIR}}"
    } > "${LAUNCH_ENV}"
}

set_common_profile_env() {
    export RELAX_TB_EXPERIMENT_NAME="${TB_EXPERIMENT_NAME}"
    export RELAX_TIMELINE_DUMP_DIR="${USER_RELAX_TIMELINE_DUMP_DIR:-${TIMELINE_DIR}}"
}

run_timeline_pass() {
    set_common_profile_env
    export RELAX_USE_PYTORCH_PROFILER="${USER_RELAX_USE_PYTORCH_PROFILER:-0}"
    export RELAX_SGLANG_PROFILE="${USER_RELAX_SGLANG_PROFILE:-0}"
    unset RELAX_PROFILE_TARGETS RELAX_PROFILE_STEP_START RELAX_PROFILE_STEP_END
    unset RELAX_SGLANG_PROFILE_STEP_START RELAX_SGLANG_PROFILE_STEP_END RELAX_SGLANG_PROFILE_STEPS

    {
        echo
        echo "===== fully_async profiling pass: timeline ====="
        date '+%Y-%m-%d %H:%M:%S %Z'
    } >> "${RUN_LOG}"
    bash "${BASE_LAUNCHER}"
}

run_focused_pass() {
    set_common_profile_env
    export RELAX_USE_PYTORCH_PROFILER="${USER_RELAX_USE_PYTORCH_PROFILER:-1}"
    export RELAX_PROFILE_TARGETS="${USER_RELAX_PROFILE_TARGETS:-train_overall train_actor train_log_probs}"
    export RELAX_PROFILE_STEP_START="${USER_RELAX_PROFILE_STEP_START:-1}"
    export RELAX_PROFILE_STEP_END="${USER_RELAX_PROFILE_STEP_END:-2}"
    export RELAX_PROFILE_WITH_STACK="${USER_RELAX_PROFILE_WITH_STACK:-0}"
    export RELAX_PROFILE_WITH_MEMORY="${USER_RELAX_PROFILE_WITH_MEMORY:-0}"
    export RELAX_PROFILE_WITH_FLOPS="${USER_RELAX_PROFILE_WITH_FLOPS:-0}"

    export RELAX_SGLANG_PROFILE="${USER_RELAX_SGLANG_PROFILE:-1}"
    export RELAX_SGLANG_PROFILE_STEP_START="${USER_RELAX_SGLANG_PROFILE_STEP_START:-1}"
    export RELAX_SGLANG_PROFILE_STEP_END="${USER_RELAX_SGLANG_PROFILE_STEP_END:-2}"
    export RELAX_SGLANG_PROFILE_STEPS="${USER_RELAX_SGLANG_PROFILE_STEPS:-}"
    export RELAX_SGLANG_PROFILE_NUM_STEPS="${USER_RELAX_SGLANG_PROFILE_NUM_STEPS:-3}"
    export RELAX_SGLANG_PROFILE_ACTIVITIES="${USER_RELAX_SGLANG_PROFILE_ACTIVITIES:-}"
    export RELAX_SGLANG_PROFILE_BY_STAGE="${USER_RELAX_SGLANG_PROFILE_BY_STAGE:-0}"
    export RELAX_SGLANG_PROFILE_WITH_STACK="${USER_RELAX_SGLANG_PROFILE_WITH_STACK:-0}"
    export RELAX_SGLANG_PROFILE_RECORD_SHAPES="${USER_RELAX_SGLANG_PROFILE_RECORD_SHAPES:-0}"
    export RELAX_SGLANG_PROFILE_OUTPUT_DIR="${USER_RELAX_SGLANG_PROFILE_OUTPUT_DIR:-${SGLANG_TRACE_DIR}}"

    {
        echo
        echo "===== fully_async profiling pass: focused ====="
        date '+%Y-%m-%d %H:%M:%S %Z'
    } >> "${RUN_LOG}"
    bash "${BASE_LAUNCHER}"
}

write_launch_env

case "${RELAX_PROFILE_PASS}" in
    timeline)
        run_timeline_pass
        ;;
    focused)
        run_focused_pass
        ;;
    both)
        run_timeline_pass
        run_focused_pass
        ;;
    *)
        echo "RELAX_PROFILE_PASS must be timeline, focused, or both; got ${RELAX_PROFILE_PASS}" >&2
        exit 2
        ;;
esac

python3 "${ROOT_DIR}/scripts/tools/summarize_fully_async_profile.py" --profile-root "${PROFILE_ROOT}"
echo "Profile artifacts written to ${PROFILE_ROOT}"
