#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

export MODEL_CONFIG_NAME="${MODEL_CONFIG_NAME:-qwen3-0.6B}"
export MODEL_ASSET_NAME="${MODEL_ASSET_NAME:-Qwen3-0.6B}"
export MODEL_LOG_NAME="${MODEL_LOG_NAME:-qwen3-0.6b}"
export RELAX_HIP_VISIBLE_DEVICES_OVERRIDE="${TINY_HIP_VISIBLE_DEVICES:-0,1}"
export HIP_VISIBLE_DEVICES="${RELAX_HIP_VISIBLE_DEVICES_OVERRIDE}"
export RAY_NUM_GPUS="${TINY_RAY_NUM_GPUS:-2}"
export ACTOR_RESOURCE_GPUS="${TINY_ACTOR_RESOURCE_GPUS:-1}"
export ROLLOUT_RESOURCE_GPUS="${TINY_ROLLOUT_RESOURCE_GPUS:-1}"
export TENSOR_MODEL_PARALLEL_SIZE="${TINY_TENSOR_MODEL_PARALLEL_SIZE:-1}"
export ENABLE_SEQUENCE_PARALLEL="${TINY_ENABLE_SEQUENCE_PARALLEL:-0}"

exec "${ROOT_DIR}/amd_qwen3_4b_2gpu_e2e.sh"
