#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

export MODEL_CONFIG_NAME="${MODEL_CONFIG_NAME:-qwen3-0.6B}"
export MODEL_ASSET_NAME="${MODEL_ASSET_NAME:-Qwen3-0.6B}"
export MODEL_LOG_NAME="${MODEL_LOG_NAME:-qwen3-0.6b}"
export CONDA_ENV_NAME="${CONDA_ENV_NAME:-relaxrl_rocm_after_fix}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export WANDB_ENTITY="${WANDB_ENTITY:-}"

export RELAX_HIP_VISIBLE_DEVICES_OVERRIDE="${RELAX_HIP_VISIBLE_DEVICES_OVERRIDE:-${HIP_VISIBLE_DEVICES:-0,1,2,3}}"
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-${RELAX_HIP_VISIBLE_DEVICES_OVERRIDE}}"
export RAY_NUM_GPUS="${RAY_NUM_GPUS:-4}"
export NUM_GPUS_PER_NODE="${NUM_GPUS_PER_NODE:-4}"
export ACTOR_RESOURCE_GPUS="${ACTOR_RESOURCE_GPUS:-2}"
export ROLLOUT_RESOURCE_GPUS="${ROLLOUT_RESOURCE_GPUS:-1}"
export ACTOR_FWD_RESOURCE_GPUS="${ACTOR_FWD_RESOURCE_GPUS:-1}"

# Training DP: two actor GPUs with Megatron TP/PP/CP all set to 1.
export TENSOR_MODEL_PARALLEL_SIZE="${TENSOR_MODEL_PARALLEL_SIZE:-1}"
export PIPELINE_MODEL_PARALLEL_SIZE="${PIPELINE_MODEL_PARALLEL_SIZE:-1}"
export CONTEXT_PARALLEL_SIZE="${CONTEXT_PARALLEL_SIZE:-1}"
export ENABLE_SEQUENCE_PARALLEL="${ENABLE_SEQUENCE_PARALLEL:-0}"

# Inference: one rollout GPU plus one actor_fwd GPU for bounded-staleness fully_async.
export ROLLOUT_NUM_GPUS_PER_ENGINE="${ROLLOUT_NUM_GPUS_PER_ENGINE:-1}"
export SGLANG_PIPELINE_PARALLEL_SIZE="${SGLANG_PIPELINE_PARALLEL_SIZE:-1}"
export SGLANG_DATA_PARALLEL_SIZE="${SGLANG_DATA_PARALLEL_SIZE:-1}"
export SGLANG_EXPERT_PARALLEL_SIZE="${SGLANG_EXPERT_PARALLEL_SIZE:-1}"
export SGLANG_ENABLE_DP_ATTENTION="${SGLANG_ENABLE_DP_ATTENTION:-0}"

# Execution mode. `fully_async` uses two actor GPUs, one rollout GPU, and one
# actor_fwd GPU so max_staleness can be greater than zero.
export RELAX_EXECUTION_MODE="${RELAX_EXECUTION_MODE:-fully_async}"

case "${RELAX_EXECUTION_MODE}" in
    fully_async)
        DEFAULT_MAX_STALENESS=1
        DEFAULT_NUM_STEPS_PER_ROLLOUT=2
        DEFAULT_ROLLOUT_BATCH_SIZE=2
        ;;
    hybrid)
        DEFAULT_MAX_STALENESS=2
        DEFAULT_NUM_STEPS_PER_ROLLOUT=1
        DEFAULT_ROLLOUT_BATCH_SIZE=2
        ;;
    sync)
        DEFAULT_MAX_STALENESS=0
        DEFAULT_NUM_STEPS_PER_ROLLOUT=2
        DEFAULT_ROLLOUT_BATCH_SIZE=2
        ;;
    *)
        echo "RELAX_EXECUTION_MODE must be fully_async, hybrid, or sync; got ${RELAX_EXECUTION_MODE}" >&2
        exit 2
        ;;
esac

# Asynchronous RL settings.
export MAX_STALENESS="${MAX_STALENESS:-${DEFAULT_MAX_STALENESS}}"

# Training length and batch sizing.
export NUM_ROLLOUT="${NUM_ROLLOUT:-2}"
export NUM_STEPS_PER_ROLLOUT="${NUM_STEPS_PER_ROLLOUT:-${DEFAULT_NUM_STEPS_PER_ROLLOUT}}"
export MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-1}"

# Inference rollout batch sizing.
export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-${DEFAULT_ROLLOUT_BATCH_SIZE}}"
export N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-2}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-$((ROLLOUT_BATCH_SIZE * N_SAMPLES_PER_PROMPT / NUM_STEPS_PER_ROLLOUT))}"
export SGLANG_SERVER_CONCURRENCY="${SGLANG_SERVER_CONCURRENCY:-16}"
export SGLANG_MAX_RUNNING_REQUESTS="${SGLANG_MAX_RUNNING_REQUESTS:-128}"
export SGLANG_MAX_TOTAL_TOKENS="${SGLANG_MAX_TOTAL_TOKENS:-65536}"
export SGLANG_MEM_FRACTION_STATIC="${SGLANG_MEM_FRACTION_STATIC:-0.2}"
export GPU_LABEL="${GPU_LABEL:-4gpu-fully-async}"

# Sequence-length sizing.
export SEQ_LENGTH="${SEQ_LENGTH:-1024}"
export ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN:-128}"
export ROLLOUT_MAX_CONTEXT_LEN="${ROLLOUT_MAX_CONTEXT_LEN:-}"
export ROLLOUT_MAX_PROMPT_LEN="${ROLLOUT_MAX_PROMPT_LEN:-}"

exec "${SCRIPT_DIR}/amd_qwen3_4b_2gpu_e2e.sh"
