#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

export MODEL_CONFIG_NAME="${MODEL_CONFIG_NAME:-qwen3-mock}"
export MODEL_ASSET_NAME="${MODEL_ASSET_NAME:-Qwen3-Mock-0.5B}"
export MODEL_LOG_NAME="${MODEL_LOG_NAME:-qwen3-mock-0.5b}"
export SAVE_CHECKPOINTS="${SAVE_CHECKPOINTS:-0}"
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-0,1}"
export RAY_NUM_GPUS="${RAY_NUM_GPUS:-2}"
export ACTOR_RESOURCE_GPUS="${ACTOR_RESOURCE_GPUS:-1}"
export ROLLOUT_RESOURCE_GPUS="${ROLLOUT_RESOURCE_GPUS:-1}"
export TENSOR_MODEL_PARALLEL_SIZE="${TENSOR_MODEL_PARALLEL_SIZE:-1}"
export ENABLE_SEQUENCE_PARALLEL="${ENABLE_SEQUENCE_PARALLEL:-0}"
export SGLANG_MEM_FRACTION_STATIC="${SGLANG_MEM_FRACTION_STATIC:-0.2}"
export SGLANG_MAX_TOTAL_TOKENS="${SGLANG_MAX_TOTAL_TOKENS:-65536}"
export SGLANG_MAX_RUNNING_REQUESTS="${SGLANG_MAX_RUNNING_REQUESTS:-128}"
export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-1}"
export N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-2}"
export ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN:-64}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-1}"

exec "${ROOT_DIR}/amd_qwen3_4b_2gpu_e2e.sh"
