#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

export MODEL_CONFIG_NAME="${MODEL_CONFIG_NAME:-qwen3-mock}"
export MODEL_ASSET_NAME="${MODEL_ASSET_NAME:-Qwen3-Mock-0.5B}"
export MODEL_LOG_NAME="${MODEL_LOG_NAME:-qwen3-mock-0.5b}"
export SAVE_CHECKPOINTS="${SAVE_CHECKPOINTS:-0}"
export RELAX_HIP_VISIBLE_DEVICES_OVERRIDE="${MOCK_HIP_VISIBLE_DEVICES:-0,1}"
export HIP_VISIBLE_DEVICES="${RELAX_HIP_VISIBLE_DEVICES_OVERRIDE}"
export RAY_NUM_GPUS="${MOCK_RAY_NUM_GPUS:-2}"
export ACTOR_RESOURCE_GPUS="${MOCK_ACTOR_RESOURCE_GPUS:-1}"
export ROLLOUT_RESOURCE_GPUS="${MOCK_ROLLOUT_RESOURCE_GPUS:-1}"
export TENSOR_MODEL_PARALLEL_SIZE="${MOCK_TENSOR_MODEL_PARALLEL_SIZE:-1}"
export ENABLE_SEQUENCE_PARALLEL="${MOCK_ENABLE_SEQUENCE_PARALLEL:-0}"
export SGLANG_MEM_FRACTION_STATIC="${MOCK_SGLANG_MEM_FRACTION_STATIC:-0.2}"
export SGLANG_MAX_TOTAL_TOKENS="${MOCK_SGLANG_MAX_TOTAL_TOKENS:-65536}"
export SGLANG_MAX_RUNNING_REQUESTS="${MOCK_SGLANG_MAX_RUNNING_REQUESTS:-128}"
export ROLLOUT_BATCH_SIZE="${MOCK_ROLLOUT_BATCH_SIZE:-1}"
export N_SAMPLES_PER_PROMPT="${MOCK_N_SAMPLES_PER_PROMPT:-2}"
export ROLLOUT_MAX_RESPONSE_LEN="${MOCK_ROLLOUT_MAX_RESPONSE_LEN:-64}"
export GLOBAL_BATCH_SIZE="${MOCK_GLOBAL_BATCH_SIZE:-1}"

exec "${ROOT_DIR}/amd_qwen3_4b_2gpu_e2e.sh"
