#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/../../.." &>/dev/null && pwd)"

cd "${ROOT_DIR}"

# Keep Ray from inheriting an incompatible ROCm device mask; the lower-level
# launcher starts a fresh local Ray head and sets HIP_VISIBLE_DEVICES instead.
unset ROCR_VISIBLE_DEVICES

export CONDA_ENV_NAME="${CONDA_ENV_NAME:-relaxrl_rocm_after_fix}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export WANDB_ENTITY="${WANDB_ENTITY:-}"

export RELAX_EXECUTION_MODE="${RELAX_EXECUTION_MODE:-fully_async}"
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-0,1,2,3}"
export RELAX_HIP_VISIBLE_DEVICES_OVERRIDE="${RELAX_HIP_VISIBLE_DEVICES_OVERRIDE:-${HIP_VISIBLE_DEVICES}}"
export RAY_NUM_GPUS="${RAY_NUM_GPUS:-4}"
export NUM_GPUS_PER_NODE="${NUM_GPUS_PER_NODE:-4}"
export ACTOR_RESOURCE_GPUS="${ACTOR_RESOURCE_GPUS:-2}"
export ROLLOUT_RESOURCE_GPUS="${ROLLOUT_RESOURCE_GPUS:-1}"
export ACTOR_FWD_RESOURCE_GPUS="${ACTOR_FWD_RESOURCE_GPUS:-1}"

export TENSOR_MODEL_PARALLEL_SIZE="${TENSOR_MODEL_PARALLEL_SIZE:-1}"
export PIPELINE_MODEL_PARALLEL_SIZE="${PIPELINE_MODEL_PARALLEL_SIZE:-1}"
export CONTEXT_PARALLEL_SIZE="${CONTEXT_PARALLEL_SIZE:-1}"
export ENABLE_SEQUENCE_PARALLEL="${ENABLE_SEQUENCE_PARALLEL:-0}"

export ROLLOUT_NUM_GPUS_PER_ENGINE="${ROLLOUT_NUM_GPUS_PER_ENGINE:-1}"
export SGLANG_PIPELINE_PARALLEL_SIZE="${SGLANG_PIPELINE_PARALLEL_SIZE:-1}"
export SGLANG_DATA_PARALLEL_SIZE="${SGLANG_DATA_PARALLEL_SIZE:-1}"
export SGLANG_EXPERT_PARALLEL_SIZE="${SGLANG_EXPERT_PARALLEL_SIZE:-1}"
export SGLANG_ENABLE_DP_ATTENTION="${SGLANG_ENABLE_DP_ATTENTION:-0}"

export MAX_STALENESS="${MAX_STALENESS:-1}"
export NUM_ROLLOUT="${NUM_ROLLOUT:-2}"
export NUM_STEPS_PER_ROLLOUT="${NUM_STEPS_PER_ROLLOUT:-2}"
export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-2}"
export N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-2}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-2}"
export MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-1}"

export SEQ_LENGTH="${SEQ_LENGTH:-1024}"
export ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN:-128}"

export SGLANG_SERVER_CONCURRENCY="${SGLANG_SERVER_CONCURRENCY:-16}"
export SGLANG_MAX_RUNNING_REQUESTS="${SGLANG_MAX_RUNNING_REQUESTS:-128}"
export SGLANG_MAX_TOTAL_TOKENS="${SGLANG_MAX_TOTAL_TOKENS:-65536}"
export SGLANG_MEM_FRACTION_STATIC="${SGLANG_MEM_FRACTION_STATIC:-0.2}"

export RELAX_USE_WANDB="${RELAX_USE_WANDB:-1}"
export RELAX_USE_METRICS_SERVICE="${RELAX_USE_METRICS_SERVICE:-1}"
export RELAX_DISABLE_SAVE="${RELAX_DISABLE_SAVE:-0}"
export RELAX_SKIP_INITIAL_FULLY_ASYNC_WEIGHT_UPDATE="${RELAX_SKIP_INITIAL_FULLY_ASYNC_WEIGHT_UPDATE:-0}"

printf 'Running Qwen3-0.6B 4-GPU fully_async e2e from %s\n' "${ROOT_DIR}" >&2
printf '  env: %s, GPUs: %s, rollouts: %s, seq_len: %s, response_len: %s\n' \
    "${CONDA_ENV_NAME}" \
    "${HIP_VISIBLE_DEVICES}" \
    "${NUM_ROLLOUT}" \
    "${SEQ_LENGTH}" \
    "${ROLLOUT_MAX_RESPONSE_LEN}" >&2

exec "${SCRIPT_DIR}/amd_qwen3_0_6b_4gpu_e2e.sh" "$@"
